import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/auth-session-provider";
import { ThemeProvider } from "@/components/navigation/providers/theme-provider";
import Providers from "@/components/navigation/providers/QueryClientProvider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Kimia Omran",
  description: "Generated by create Liaqat Paindah",
  icons: {
    icon: "/fav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthSessionProvider>
            <Providers> {children}</Providers>
          </AuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
